function G_fix = getG(q0,q1,q2)
%GETG
%    G_FIX = GETG(MASS,Q0,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    19-Mar-2018 16:49:18
mass = 1
t2 = sqrt(2.0);
t3 = cos(q0);
t4 = cos(q1);
t5 = pi.*(1.0./2.0);
t6 = q2+t5;
t7 = sin(q1);
t8 = cos(t6);
t9 = sin(q0);
t10 = sin(t6);
t11 = mass.*t2.*t4.*t8.*7.848e-1;
t12 = mass.*t2.*t7.*t9.*t10.*4.805514039854214e-17;
G_fix = [mass.*t2.*t3.*t7.*(-1.261447435461731e-16)-mass.*t2.*t4.*t9.*2.0601-mass.*t2.*t3.*t4.*t10.*4.805514039854214e-17-mass.*t2.*t3.*t7.*t8.*4.805514039854214e-17-mass.*t2.*t4.*t8.*t9.*7.848e-1+mass.*t2.*t7.*t9.*t10.*7.848e-1;t11+t12+mass.*t2.*t4.*2.0601-mass.*t2.*t3.*t7.*2.0601-mass.*t2.*t4.*t9.*1.261447435461731e-16-mass.*t2.*t7.*t10.*7.848e-1-mass.*t2.*t3.*t4.*t10.*7.848e-1-mass.*t2.*t3.*t7.*t8.*7.848e-1-mass.*t2.*t4.*t8.*t9.*4.805514039854214e-17;t11+t12-mass.*t2.*t7.*t10.*7.848e-1-mass.*t2.*t3.*t4.*t10.*7.848e-1-mass.*t2.*t3.*t7.*t8.*7.848e-1-mass.*t2.*t4.*t8.*t9.*4.805514039854214e-17];
