function G_fix = getG(q0,q1,q2)
%GETG
%    G_FIX = GETG(MASS,Q0,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    21-Mar-2018 14:25:08
mass = 5;

t2 = sqrt(2.0);
t3 = pi.*(1.0./2.0);
t4 = q0+t3;
t5 = cos(q1);
t6 = cos(t4);
t7 = sin(t4);
t8 = cos(q2);
t9 = sin(q1);
t10 = sin(q2);
t11 = mass.*t2.*t5.*t8.*(9.81e2./6.25e2);
t12 = mass.*t2.*t5.*t6.*t8.*9.611028079708428e-17;
G_fix = [mass.*t2.*t5.*t6.*3.09015-mass.*t2.*t7.*t9.*1.892171153192597e-16+mass.*t2.*t5.*t6.*t8.*(9.81e2./6.25e2)-mass.*t2.*t5.*t7.*t10.*9.611028079708428e-17-mass.*t2.*t7.*t8.*t9.*9.611028079708428e-17-mass.*t2.*t6.*t9.*t10.*(9.81e2./6.25e2);t11+t12+mass.*t2.*t5.*3.09015+mass.*t2.*t5.*t6.*1.892171153192597e-16-mass.*t2.*t7.*t9.*3.09015-mass.*t2.*t9.*t10.*(9.81e2./6.25e2)-mass.*t2.*t5.*t7.*t10.*(9.81e2./6.25e2)-mass.*t2.*t7.*t8.*t9.*(9.81e2./6.25e2)-mass.*t2.*t6.*t9.*t10.*9.611028079708428e-17;t11+t12-mass.*t2.*t9.*t10.*(9.81e2./6.25e2)-mass.*t2.*t5.*t7.*t10.*(9.81e2./6.25e2)-mass.*t2.*t7.*t8.*t9.*(9.81e2./6.25e2)-mass.*t2.*t6.*t9.*t10.*9.611028079708428e-17];
