function G_fix = getG(q0,q1,q2)
%GETG
%    G_FIX = GETG(MASS,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    20-Mar-2018 08:44:03
mass = 1;
t2 = cos(q1);
t3 = pi.*(1.0./2.0);
t4 = q2+t3;
t5 = cos(t4);
t6 = mass.*t2.*t5.*(9.81e2./6.25e2);
t7 = sin(q1);
t8 = sin(t4);
G_fix = [0.0;t6+mass.*t2.*4.1202-mass.*t7.*t8.*(9.81e2./6.25e2);t6-mass.*t7.*t8.*(9.81e2./6.25e2)];
    